# Generated by Django 4.1.7 on 2023-05-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_watchlist_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='watchlists', to='auctions.listing'),
        ),
    ]
